# Generated by Django 3.2.19 on 2023-06-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_date_time',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
    ]
